name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics part 1
        uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AWildLeon
          template: classic
          filename: .generated/metrics-left.svg
          base: header, activity, community, repositories
          config_timezone: Europe/Berlin
          
          plugin_introduction: no
          plugin_introduction_title: yes

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_traffic: yes

      - name: Generate metrics part 2
        uses: lowlighter/metrics@366f8b9dfe3a59656c67d5dcad9950f59c9bc96d
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: AWildLeon
          template: classic
          filename: .generated/metrics-right.svg
          base: metadata
          config_timezone: Europe/Berlin
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
  
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
